os: linux
dist: focal
language: java
services:
  - docker
install: skip

stages:
  - name: test

jobs:
  include:
    - stage: test
      name: "Test"
      script:
        - mvn test

after_success:
  - echo passed
  - echo $TRAVIS_TEST_RESULT

after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
