os: linux

language: java
services:
  - docker
cache: bundler
dist: focal

install: skip

jobs:
  include:
    - name: testing
      script: true

after_success:
  - echo passed
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
